use_frameworks!

target 'SirioLibanesApp_Example' do
  pod 'SirioLibanesApp', :path => '../'
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
   pod 'PKHUD'
   pod 'BarcodeScanner', '4.1.2'
   pod 'MYTableViewIndex'
   pod 'PureLayout'
   pod "QRCode"

  target 'SirioLibanesApp_Tests' do
    inherit! :search_paths
    pod 'Quick', '~> 1.2.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
